### ISSUE TITLE
Giant Bat mod "Screech, Sonic Burst, and Deathscream deal 256 Nature damage over 8 seconds" adds a trauma dot as well as nature

### ISSUE THREAD

**Issue by TrdColin** [orakulam/pgsim#19]
Pick Giant Bat then any one or more of screech, sonic burst and deathscream as well as the listed mod and it will add a trauma dot alongside the nature dot.

**Comment by orakulam** [comment]
Thanks @TrdColin!

Notes for fixing: this issue appears with abilities with multiple dots, because we're incorrectly adding `DotDamage` to all dots on the ability.

List below with abilities that have this issue. The problem is that there's no super clear way to differentiate multiple dots on the same ability. Some differ in `num_ticks` (delayed damage), some differ in duration, and one only differs in damage type (Heart Thorn). 

Likely fix: parse out `num_ticks`, duration, and damage type from every dot mod, then match against that when finding which dot to add damage to.

```
Sanguine Fangs 4
    delayed damage
Fire Arrow 8
    delayed damage
Spit Acid 6
    two dots, different duration
Boiling Veins
    delayed damage
Molten Veins 6
    delayed damage
Fire Shield 6
    delayed damage
Drink Blood 8
    delayed damage
Screech 8
    two dots, different duration
Sonic Burst 8
    two dots, different duration
Deathscream 6
    two dots, different duration
Heart Thorn 9
    two dots, same duration, different damage type
Sanguine Fangs 7
    delayed damage
Privacy Field 5
    delayed damage
```
